### ISSUE TITLE
assertion error?

### ISSUE THREAD

**Issue by enchilada404** [gesellkammer/loristrck#1]
I finally managed to compile loristrck using WSL(with ubuntu 18.04 bash terminal, no gui) on windows 10!!! :)

However, when I try pack partials, I get an assertion error, like this:

enchilada@DESKTOP-SQV58NJ:~$ loristrck_pack beat1.wav
Traceback (most recent call last):
  File "/home/enchilada/.local/bin/loristrck_pack", line 68, in <module>
    loristrck.partials_save_matrix(selected_partials, dt=dt, outfile=outfile, maxactive=args.maxoscil, maxtracks=args.maxtracks)
  File "/home/enchilada/.local/lib/python3.6/site-packages/loristrck/util.py", line 652, in partials_save_matrix
    tracks, rest = pack(partials, gap=dt*gapfactor, maxtracks=maxtracks)
  File "/home/enchilada/.local/lib/python3.6/site-packages/loristrck/util.py", line 189, in pack
    joint_tracks = [_join_track(track, fade=fade) for track in tracks]
  File "/home/enchilada/.local/lib/python3.6/site-packages/loristrck/util.py", line 189, in <listcomp>
    joint_tracks = [_join_track(track, fade=fade) for track in tracks]
  File "/home/enchilada/.local/lib/python3.6/site-packages/loristrck/util.py", line 119, in _join_track
    assert p[0, 2] == 0
AssertionError

Do I have to feed it a fade value, or am I doing something else wrong?

**Comment by gesellkammer** [comment]
could you post the soundfile?

**Comment by enchilada404** [comment]
sure,

it's a standard wav 16 bit 44100 hz mono file:

(had to zip it to attach)

[beat1.zip](https://github.com/gesellkammer/loristrck/files/4125018/beat1.zip)

I have also tried other soundfiles with the same result.

**Comment by gesellkammer** [comment]
ok, fixed in git.
