### ISSUE TITLE
Version in pip not working for Windows 11 Python 3.10

### ISSUE THREAD

**Issue by charlesneimog** [gesellkammer/loristrck#7]
Hi, I am trying to `pip install loristrck`, and I am getting this error: 

```
error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Neimog\AppData\Local\Temp\pip-install-7464h7zk\loristrck_7990e39ca4214441885f7e96c97a3f9e\setup.py", line 70, in <module>
          assert os.path.exists('src/loriswin'), (
      AssertionError: Source files for windows not found. From a 'Developer Command Prompt' run scripts/prepare_windows_build.py first
      Platform win32
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
``` 
It is possible to compile it using the README, but could you add the wheel in the pip too?

[loristrck-1.4.0-cp310-cp310-win_amd64.zip](https://github.com/gesellkammer/loristrck/files/9579598/loristrck-1.4.0-cp310-cp310-win_amd64.zip)

**OBS.:** In the compilation, I had the warning with `ssize_t` and `Py_ssize_t`, but this time no error when compiling.

Amazing work, thanks again!

**Comment by gesellkammer** [comment]
I don't have means to test this on windows at the moment. Could you try to fix it and make a PR?

**Comment by charlesneimog** [comment]
#10
